---

- name: Create ddclient namespace
  kubernetes.core.k8s:
    name: '{{ ddclient_namespace }}'
    api_version: v1
    kind: Namespace

- name: Deploy ddclient
  kubernetes.core.k8s:
    namespace: '{{ ddclient_namespace }}'
    template: '{{ item }}'
  with_items:
    - deployment.yaml.j2
    - ddclient-secret.yaml.j2
